name: practical_google_maps_example
description: "A new Flutter project."

publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  custom_info_window: ^1.0.1
  geocoding: ^3.0.0
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_remote_config: ^5.4.0
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  go_router: ^14.6.2
  flutter_screenutil: ^5.9.3
  go_transitions: ^0.7.1
  get_it: ^8.0.3
  flutter_secure_storage: ^9.2.4
  animated_snack_bar: ^0.4.0
  flutter_bloc: ^9.0.0
  dartz: ^0.10.1
  intl: ^0.20.2
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/icons/



